bot:
  abi_migration_branches:
  - v1.74.x
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: emulated
  win: azure
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
azure:
  store_build_artifacts: true
